name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup MoonBit
        uses: moonbitlang/setup-moonbit@v1
        with:
          moonbit-version: 0.10.3

      - name: Show MoonBit Version
        run: moon version --all

      - name: moon fmt check
        run: moon fmt --check
        
      - name: moon info check
        run: moon info
        
      - name: moon check
        run: moon check --deny-warn

      - name: moon build
        run: moon build

      - name: moon test
        run: moon test
